# Spring Boot configuration
spring:

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    generate-ddl: true

  # Logger configuration
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug

# Server configuration
server:
  port: 8080